repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
        - id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
        - id: flake8
          args:
              - "--max-line-length=160"
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.1
    hooks:
         - id: terraform_fmt
         - id: terraform_validate
